package dottytags

import TagClass._

// This whole file is, of course, derived from scalatags.

object SvgTags {

  inline def altGlyph = tag("altGlyph")
  inline def altGlyphDef = tag("altGlyphDef")
  inline def altGlyphItem = tag("altGlyphItem")
  inline def animate = tag("animate")
  inline def animateMotion = tag("animateMotion")
  inline def animateTransform = tag("animateTransform")
  inline def circle = tag("circle")
  inline def clipPath = tag("clipPath")
  inline def `color-profile` = tag("color-profile")
  inline def cursor = tag("cursor")
  inline def defs = tag("defs")
  inline def desc = tag("desc")
  inline def ellipse = tag("ellipse")
  inline def feBlend = tag("feBlend")
  inline def feColorMatrix = tag("feColorMatrix")
  inline def feComponentTransfer = tag("feComponentTransfer")
  inline def feComposite = tag("feComposite")
  inline def feConvolveMatrix = tag("feConvolveMatrix")
  inline def feDiffuseLighting = tag("feDiffuseLighting")
  inline def feDisplacementMap = tag("feDisplacementMap")
  inline def feDistantLighting = tag("feDistantLighting")
  inline def feFlood = tag("feFlood")
  inline def feFuncA = tag("feFuncA")
  inline def feFuncB = tag("feFuncB")
  inline def feFuncG = tag("feFuncG")
  inline def feFuncR = tag("feFuncR")
  inline def feGaussianBlur = tag("feGaussianBlur")
  inline def feImage = tag("feImage")
  inline def feMerge = tag("feMerge")
  inline def feMergeNode = tag("feMergeNode")
  inline def feMorphology = tag("feMorphology")
  inline def feOffset = tag("feOffset")
  inline def fePointLight = tag("fePointLight")
  inline def feSpecularLighting = tag("feSpecularLighting")
  inline def feSpotlight = tag("feSpotlight")
  inline def feTile = tag("feTile")
  inline def feTurbulance = tag("feTurbulance")
  inline def filter = tag("filter")
  inline def font = tag("font")
  inline def `font-face` = tag("font-face")
  inline def `font-face-format` = tag("font-face-format")
  inline def `font-face-name` = tag("font-face-name")
  inline def `font-face-src` = tag("font-face-src")
  inline def `font-face-uri` = tag("font-face-uri")
  inline def foreignObject = tag("foreignObject")
  inline def g = tag("g")
  inline def glyph = tag("glyph")
  inline def glyphRef = tag("glyphRef")
  inline def hkern = tag("hkern")
  inline def image = tag("image")
  inline def line = tag("line")
  inline def linearGradient = tag("linearGradient")
  inline def marker = tag("marker")
  inline def mask = tag("mask")
  inline def metadata = tag("metadata")
  inline def `missing-glyph` = tag("missing-glyph")
  inline def mpath = tag("mpath")
  inline def path = tag("path")
  inline def pattern = tag("pattern")
  inline def polygon = tag("polygon")
  inline def polyline = tag("polyline")
  inline def radialGradient = tag("radialGradient")
  inline def rect = tag("rect")
  inline def set = tag("set")
  inline def stop = tag("stop")
  inline def svg = tag("svg")
  inline def switch = tag("switch")
  inline def symbol = tag("symbol")
  inline def text = tag("text")
  inline def textPath = tag("textPath")
  inline def tref = tag("tref")
  inline def tspan = tag("tspan")
  inline def use = tag("use")
  inline def view = tag("view")
  inline def vkern = tag("vkern")
  
}